name: output infor
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event name is:" ${{ github.event_name }}
      - run: echo "event type is:" ${{ github.event.action }}
